# Generated by Django 2.1.2 on 2019-07-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Twitters',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('removed', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('tweetdate', models.DateTimeField(auto_now_add=True)),
                ('nick', models.CharField(blank=True, max_length=15, null=True)),
                ('tweet', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
